name: Mon Premier Workflow
on: workflow_dispatch
jobs:
  premierJob:
    run-on: ubuntu-latest
    steps: 
      - name: Mon premier Job
        run: echo "Démarrages des choses"
      - name: Mes premières instructions
        run: ls /
      - name: Fin du premier Job 
        run: echo "That's all trucs"
